### ISSUE TITLE
There was an error converting the video.

### ISSUE THREAD

**Issue by pradeepnitsan** [passionweb-manuel-schnabel/webm#1]
Hello,

I have installed this extension (version 2.1.2) in TYPO3 version 12.4.8 with PHP version 8.2

And I am facing the issue when I save the video -
**Screenshot:**

![converting_video_issue](https://github.com/passionweb-manuel-schnabel/webm/assets/151850231/e510bba1-2bfa-44d9-ae3f-457bcefdaf74)

I have also tried with the Scheduled tasks but not showing the webm format in the Filelist module.
**Screenshot:**

![scheduler_issue](https://github.com/passionweb-manuel-schnabel/webm/assets/151850231/4b0aaffa-6c89-45a6-9cb7-c562acfea554)

Can you please help me with this how can I fix this? it's urgent for me.

Thanks!

**Comment by passionweb-manuel-schnabel** [comment]
Hello @pradeepnitsan ,

thansk for your request. 

I will try to recreate this issue and then get back to you (if necessary with further information that I need).

Best regards

Manu

**Comment by passionweb-manuel-schnabel** [comment]
Hello @pradeepnitsan,

I tried to recreate the error, but unfortunately I wasn't successful.

I used he following server environment and versions and its working fine:

PHP: 8.2
TYO3 12.4.8
Web server: Apache-fpm
Server: Debian 10.2.1-6
FFmpeg: 4.3.6-0+deb11u1

Could you please send me an excerpt from the TYPO3 logs where the error message is described in more detail?

Thanks in advance.

Greetings Manuel
