### ISSUE TITLE
Invalid composer version string

### ISSUE THREAD

**Issue by infabo** [passionweb-manuel-schnabel/webm#2]
https://github.com/passionweb-manuel-schnabel/webm/blob/5c56ff870fd4a84314a5545042e46b945aa7eaad/composer.json#L16

**Comment by infabo** [comment]
This should read: `^12.4 || ^13.4`

**Comment by passionweb-manuel-schnabel** [comment]
Hey @infabo ,

thanks for the hint. I've adjusted it quickly. My colleague is currently working on the migration and as far as I know it hasn't been tested further and has "only" been created initially.

Greetings Manu
